name: Docker Image CI

on:
  push:
    branches: [ feature/container ]
  pull_request:
    branches: [ feature/container ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag microsoftgraph-aspnetcore-webhooks:$(date +%s)